### ISSUE TITLE
Close all active sections

### ISSUE THREAD

**Issue by ammichael** [oblador/react-native-collapsible#29]
Hello there!

First, thanks for this amazing component. It is really awesome!

Is there a way to close all active collapsible? In my case, as an accordion, it will always have just one, but when I delete one of the sections, it automatically rearrange the accordion and it indexes, but it keeps the index opened. So I have a new section occupying the same accordion index, which is active.

Hope I made it clear!

Thanks a lot

**Comment by oblador** [comment]
Fixed in https://github.com/oblador/react-native-collapsible/releases/tag/v0.7.0

**Comment by matheusbaumgart** [comment]
I'm still having a similar issue where I change my sections as the user does something, however, if the first section is opened when the list of sections change, the new list will also have the first tab active (expanded), same applies if it's any other tab of the same index. 

Can someone please help? passing an unique `key` is not solving it.

**Comment by iRoachie** [comment]
@matheusbaumgart please create a new issue with an example on https://snack.expo.io that reproduces this
